import { api, clearSession, requireSession, showToast } from './auth.js';
if (!requireSession()) throw new Error('Authentication required');

const HEAD_OFFICE='สำนักงานใหญ่';
const BRANCHES=['สุขุมวิท 31','ราชเทวี','สาทร','เกษตร','ปิ่นเกล้า','โชคชัย 4','อารีย์','รัชดา','อ่อนนุช','สามัคคี','หัวหมาก','รัตนาธิเบศร์ 22','วงเวียนใหญ่','แบริ่ง','ศรีนครินทร์','พัฒนาการ','บางแค','เพชรเกษม48','สรงประภา','ราชพฤกษ์-สวนผัก32','ประชาอุทิศ','เคหะร่มเกล้า','เมืองเอก','ลาดกระบัง','ศาลายา','สายลม','ธรรมศาสตร์ รังสิต','ลาดพร้าว101','เยาวราช(franchise)','พระราม5(franchise)','กาดรวมโชค','สถานีรถไฟเชียงใหม่','นิมมาน','หน้าเมือง','กังสดาล','โคราช','พระราม 9','อุดร','ประชาชื่น 36','แจ้งวัฒนะ - ปากเกร็ด 36','บางแสน','บางพลี(franchise)','เพชรเกษม 69(franchise)','ยิ่งเจริญ','มมส.(franchise)','พระราม 3','สามย่าน','ลาดปลาเค้า','สนามจันทร์','รังสิต คลอง 3','คุ้มสึ บางนา'];
const ALL_BRANCHES=[HEAD_OFFICE,...BRANCHES];
const POSITIONS=['พนักงานหน้าสาขา','AM','OM','ACC','HR','Audit','Admin','Marketing','IT','Purchase','Inventory','Production','QC','Owner'];
const ISSUE_TYPES=['FoodStory','App LINE MAN, Grab, ShopeeFood, Robinhood','Internet','Accessories & Cable','Mobile','iPad','CCTV','Printer','Notebook','Email','Open Brand'];
const TYPES=['มือถือ','ไอแพด','เครื่องพิมพ์ใบเสร็จ','เครื่องปริ้น Inkjet','สายชาร์จ Type-C','สายชาร์จ iPad','โน้ตบุ๊ก','เมาส์','คีย์บอร์ด','จอคอมพิวเตอร์','CCTV'];
const BRANCH_TYPES=['มือถือ','ไอแพด','เครื่องพิมพ์ใบเสร็จ','CCTV','จอคอมพิวเตอร์','เครื่องปริ้น Inkjet'];
const STATUS={waiting:'รอดำเนินการ',progress:'กำลังดำเนินการ',urgent:'เร่งด่วน',completed:'เสร็จสิ้น'};
const TECH_NAMES={'pachara.r@kumtsu.com':'พชร รัตนเขมากร','krissana.s@kumtsu.com':'กฤษณะ ศรีล้านมี'};
const $=id=>document.getElementById(id); let state={jobs:[],items:[],issues:[],profile:{},permissions:{}},selectedJob=null,calendarDate=new Date();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const jobNo=id=>`IT-${String(id).padStart(4,'0')}`;
const today=()=>new Date().toLocaleDateString('en-CA');
const thDate=v=>v?new Intl.DateTimeFormat('th-TH',{dateStyle:'medium'}).format(new Date(`${v}T00:00:00`)):'—';
const request=async(method,body)=>{const {response,data}=await api('/api/it-service',{method,body:JSON.stringify(body)});if(!response.ok)throw new Error(data.message||'ดำเนินการไม่สำเร็จ');showToast(data.message);await load();return data};

function fillOptions(){
  $('position').innerHTML='<option value="">เลือกตำแหน่ง</option>'+POSITIONS.map(x=>`<option>${x}</option>`).join('');
  $('editPosition').innerHTML=POSITIONS.map(x=>`<option>${x}</option>`).join('');
  $('issueType').innerHTML='<option value="">เลือกหัวข้อ</option>'+ISSUE_TYPES.map(x=>`<option>${x}</option>`).join('');
  $('editIssueType').innerHTML=ISSUE_TYPES.map(x=>`<option>${x}</option>`).join('');
  $('branchOptions').innerHTML=ALL_BRANCHES.map(x=>`<option value="${x}"></option>`).join('');
  $('inventoryBranch').innerHTML=ALL_BRANCHES.map(x=>`<option>${x}</option>`).join('');
  $('inventoryType').innerHTML=TYPES.map(x=>`<option>${x}</option>`).join('');
  $('stockTypeFilter').innerHTML='<option value="">ทุกประเภท</option>'+TYPES.map(x=>`<option>${x}</option>`).join('');
  $('jobBranchFilter').innerHTML='<option value="">ทุกสาขา</option>'+ALL_BRANCHES.map(x=>`<option>${x}</option>`).join('');
}
function filteredJobs(){const q=$('jobSearch').value.trim().toLowerCase(),branch=$('jobBranchFilter').value,status=$('jobStatusFilter').value;return state.jobs.filter(j=>(!q||`${jobNo(j.id)} ${j.requester_name} ${j.branch} ${j.issue_type} ${j.description}`.toLowerCase().includes(q))&&(!branch||j.branch===branch)&&(!status||j.status===status));}
function renderJobs(){
  const month=new Date(),monthly=state.jobs.filter(j=>{const d=new Date(`${j.request_date}T00:00:00`);return d.getMonth()===month.getMonth()&&d.getFullYear()===month.getFullYear()});
  $('jobStats').innerHTML=[['all','งานทั้งหมดเดือนนี้',monthly.length],...Object.entries(STATUS).map(([k,v])=>[k,v,monthly.filter(j=>j.status===k).length])].map(([k,l,n])=>`<div class="stat ${k}">${l}<b>${n}</b><small>รายการ</small></div>`).join('');
  const jobs=filteredJobs(); $('jobList').innerHTML=jobs.length?`<table><thead><tr><th>เลขที่</th><th>วันที่</th><th>ผู้แจ้ง</th><th>สาขา</th><th>ปัญหา</th><th>ผู้รับผิดชอบ</th><th>สถานะ</th><th></th></tr></thead><tbody>${jobs.map(j=>`<tr><td><b>${jobNo(j.id)}</b></td><td>${thDate(j.request_date)}</td><td>${esc(j.requester_name)}<small>${esc(j.requester_email)}</small></td><td>${esc(j.branch)}</td><td><b>${esc(j.issue_type)}</b><small>${esc(j.description)}</small></td><td>${esc((j.assigned_to||[]).map(x=>TECH_NAMES[x]||x).join(', ')||'ยังไม่ระบุ')}</td><td><span class="pill ${j.status}">${STATUS[j.status]}</span></td><td><button class="link" data-job="${j.id}">ดูงาน →</button></td></tr>`).join('')}</tbody></table>`:'<p>ยังไม่มีงานในรายการนี้</p>';
  renderCalendar();
}
function renderCalendar(){const year=calendarDate.getFullYear(),month=calendarDate.getMonth(),first=new Date(year,month,1).getDay(),days=new Date(year,month+1,0).getDate(),prev=new Date(year,month,0).getDate();let cells='';for(let i=0;i<42;i++){let day=i-first+1,muted=false;if(day<1){day=prev+day;muted=true}else if(day>days){day-=days;muted=true}const key=muted?'':`${year}-${String(month+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`,events=filteredJobs().filter(j=>(j.scheduled_date||j.request_date)===key);cells+=`<div class="calendar-day ${muted?'muted':''}"><b>${day}</b>${events.map(j=>`<button class="calendar-event" data-job="${j.id}">${jobNo(j.id)} · ${esc(j.branch)}</button>`).join('')}</div>`}$('calendar').innerHTML=`<div class="calendar-head"><button id="prevMonth">‹</button><h3>${new Intl.DateTimeFormat('th-TH',{month:'long',year:'numeric'}).format(calendarDate)}</h3><button id="nextMonth">›</button></div><div class="calendar-grid">${['อา','จ','อ','พ','พฤ','ศ','ส'].map(d=>`<div class="calendar-day"><b>${d}</b></div>`).join('')}${cells}</div>`;$('prevMonth').onclick=()=>{calendarDate=new Date(year,month-1,1);renderCalendar()};$('nextMonth').onclick=()=>{calendarDate=new Date(year,month+1,1);renderCalendar()};}
function renderInventory(){
  const available=state.items.filter(x=>x.status==='available'),pending=state.issues.filter(x=>x.old_device_status==='pending_return').reduce((n,x)=>n+x.quantity,0),repair=state.items.filter(x=>x.status==='repair'&&['มือถือ','ไอแพด'].includes(x.equipment_type)).reduce((n,x)=>n+x.quantity,0),low=available.filter(x=>x.quantity<=x.minimum_quantity).length;
  $('stockStats').innerHTML=[['','รายการทั้งหมด',state.items.length,'รายการ'],['waiting','คงเหลือทั้งหมด',available.reduce((n,x)=>n+x.quantity,0),'ชิ้น'],['progress','เครื่องเก่ายังไม่ได้รับคืน',pending,'เครื่อง'],['urgent','เครื่องรอซ่อม',repair,'มือถือ / ไอแพด'],['completed','ใกล้หมด',low,'รายการ']].map(([c,l,n,u])=>`<div class="stat ${c}">${l}<b>${n}</b><small>${u}</small></div>`).join('');
  $('stockBalances').innerHTML=TYPES.map(t=>`<div class="balance"><span>${t}</span><b>${available.filter(x=>x.equipment_type===t).reduce((n,x)=>n+x.quantity,0)}</b><small>คงเหลือ</small></div>`).join('');
  const q=$('stockSearch').value.trim().toLowerCase(),type=$('stockTypeFilter').value,items=state.items.filter(x=>(!q||`${x.equipment_type} ${x.brand} ${x.model} ${x.serial_number} ${x.branch}`.toLowerCase().includes(q))&&(!type||x.equipment_type===type));
  $('stockList').innerHTML=items.length?`<table><thead><tr><th>รหัส</th><th>อุปกรณ์</th><th>ยี่ห้อ / รุ่น / ซีเรียล</th><th>คงเหลือ</th><th>สาขา / ผู้ครอบครอง</th><th>สถานะ</th><th></th></tr></thead><tbody>${items.map(x=>`<tr><td>IT-ST-${String(x.id).padStart(4,'0')}</td><td><b>${esc(x.equipment_type)}</b></td><td>${esc(x.brand)} · ${esc(x.model)}<small>${esc(x.serial_number||'ไม่มีซีเรียล')}</small></td><td><b>${x.quantity}</b><small>ขั้นต่ำ ${x.minimum_quantity}</small></td><td>${esc(x.branch)}<small>${esc(x.storage_location)}</small></td><td><span class="pill">${x.status==='repair'?'รอซ่อม':x.status==='retired'?'เลิกใช้งาน':'พร้อมใช้'}</span></td><td class="admin-only"><button class="link" data-edit-item="${x.id}">แก้ไข</button> <button class="link" data-delete-item="${x.id}">ลบ</button>${x.status==='repair'?` <button class="link" data-repair-item="${x.id}">ซ่อมเสร็จ</button>`:''}</td></tr>`).join('')}</tbody></table>`:'<p>ยังไม่มีข้อมูลอุปกรณ์</p>'; applyPermissions();
}
function renderBranches(){
  $('branchSummary').innerHTML=BRANCH_TYPES.map(t=>`<div><span>${t}</span><b>${state.items.filter(x=>x.equipment_type===t).reduce((n,x)=>n+x.quantity,0)}</b><small>เครื่อง</small></div>`).join('');
  const q=$('branchSearch').value.trim().toLowerCase(),branches=ALL_BRANCHES.filter(x=>x.toLowerCase().includes(q));
  $('branchList').innerHTML=`<table><thead><tr><th>สาขา</th>${BRANCH_TYPES.map(t=>`<th>${t}</th>`).join('')}<th>จัดการ</th></tr></thead><tbody>${branches.map(b=>`<tr><td><b>${b}</b></td>${BRANCH_TYPES.map(t=>`<td>${state.items.filter(x=>x.branch===b&&x.equipment_type===t).reduce((n,x)=>n+x.quantity,0)}</td>`).join('')}<td><div class="branch-actions"><button class="link" data-branch="${esc(b)}">ดูข้อมูล / แก้ไข →</button><button class="primary compact admin-only" data-add-branch="${esc(b)}">＋ เพิ่มอุปกรณ์</button></div></td></tr>`).join('')}</tbody></table>`;applyPermissions();
}
function applyPermissions(){document.querySelectorAll('.admin-only').forEach(x=>x.hidden=!state.permissions.canManage)}
async function load(){const {response,data}=await api('/api/it-service');if(!response.ok)throw new Error(data.message||'โหลดข้อมูลไม่สำเร็จ');state=data;$('viewerName').textContent=`${data.profile.first_name} ${data.profile.last_name}`;$('viewerRole').textContent=data.permissions.canManage?'ผู้ดูแลระบบไอที':data.profile.email;renderJobs();renderInventory();renderBranches();applyPermissions()}

function openJob(id){selectedJob=state.jobs.find(x=>x.id===Number(id));if(!selectedJob)return;$('detailNumber').textContent=`${jobNo(id)} · ${STATUS[selectedJob.status]}`;$('jobDetails').innerHTML=[['ผู้แจ้ง',`${selectedJob.requester_name} · ${selectedJob.requester_email}`],['ตำแหน่ง',selectedJob.position],['สาขา',selectedJob.branch],['วันที่แจ้ง',thDate(selectedJob.request_date)],['หัวข้อ',selectedJob.issue_type],['รายละเอียด',selectedJob.description]].map(([a,b])=>`<div><dt>${a}</dt><dd>${esc(b)}</dd></div>`).join('');$('editRequestDate').value=selectedJob.request_date;$('editPosition').value=selectedJob.position;$('editBranch').value=selectedJob.branch;$('editIssueType').value=selectedJob.issue_type;$('editDescription').value=selectedJob.description;document.querySelectorAll('[name=assignee]').forEach(x=>x.checked=(selectedJob.assigned_to||[]).includes(x.value));$('editStatus').value=selectedJob.status;$('scheduledDate').value=selectedJob.scheduled_date||'';$('issueItem').innerHTML='<option value="">เลือกอุปกรณ์</option>'+state.items.filter(x=>x.status==='available'&&x.quantity>0).map(x=>`<option value="${x.id}">${esc(x.equipment_type)} · ${esc(x.brand)} ${esc(x.model)} ${esc(x.serial_number||'')} — คงเหลือ ${x.quantity}</option>`).join('');const issues=state.issues.filter(x=>x.job_id===selectedJob.id);$('jobIssues').innerHTML=issues.length?issues.map(x=>{const i=state.items.find(y=>y.id===x.inventory_item_id);return `<p>${esc(i?.equipment_type||'อุปกรณ์')} · ${esc(i?.brand||'')} ${esc(i?.model||'')} · S/N ${esc(i?.serial_number||'—')} × ${x.quantity}${x.old_device_status==='pending_return'?' · <b>เครื่องเก่ายังไม่ได้รับคืน</b>':''}</p>`}).join(''):'<p>ยังไม่มีการตัดสต๊อก</p>';$('receiptButton').hidden=!(selectedJob.status==='completed'&&issues.length);applyPermissions();$('detailDialog').showModal()}
function editItem(id){const x=state.items.find(y=>y.id===Number(id));if(!x)return;$('inventoryTitle').textContent='แก้ไขรายการอุปกรณ์';$('inventoryId').value=x.id;$('inventoryType').value=x.equipment_type;$('inventoryBrand').value=x.brand;$('inventoryModel').value=x.model;$('inventorySerial').value=x.serial_number||'';$('inventoryQuantity').value=x.quantity;$('inventoryMinimum').value=x.minimum_quantity;$('inventoryBranch').value=x.branch;$('inventoryLocation').value=x.storage_location;$('inventoryNote').value=x.note||'';$('inventoryDialog').showModal()}
function openInventoryForBranch(branch=HEAD_OFFICE){$('inventoryForm').reset();$('inventoryId').value='';$('inventoryTitle').textContent=`เพิ่มอุปกรณ์ · ${branch}`;$('inventoryQuantity').value=1;$('inventoryMinimum').value=0;$('inventoryBranch').value=branch;$('inventoryDialog').showModal()}
function renderBranchDevices(name){const items=state.items.filter(x=>x.branch===name);$('branchDevices').innerHTML=items.length?items.map(x=>`<article class="device-card"><div><b>${esc(x.equipment_type)} · ${esc(x.brand)} ${esc(x.model)}</b><small>ซีเรียล ${esc(x.serial_number||'—')} · จำนวน ${x.quantity} · ผู้ครอบครอง ${esc(x.storage_location)}</small></div>${state.permissions.canManage?`<div class="branch-actions"><button class="link" data-edit-item="${x.id}">แก้ไข</button><button class="link danger-link" data-delete-item="${x.id}">ลบ</button></div>`:''}</article>`).join(''):'<p>สาขานี้ยังไม่มีข้อมูลอุปกรณ์</p>'}
function openBranch(name){$('branchTitle').textContent=name;renderBranchDevices(name);$('branchDialog').showModal()}
function showReceipt(){const issues=state.issues.filter(x=>x.job_id===selectedJob.id);$('receiptNo').textContent=jobNo(selectedJob.id);$('receiptMeta').innerHTML=`<div><small>วันที่ส่งมอบ</small><b>${thDate(selectedJob.scheduled_date||selectedJob.request_date)}</b></div><div><small>ผู้รับอุปกรณ์</small><b>${esc(selectedJob.requester_name)}</b><span>${esc(selectedJob.requester_email)}</span></div><div><small>สาขา</small><b>${esc(selectedJob.branch)}</b></div><div><small>อ้างอิงงาน</small><b>${jobNo(selectedJob.id)} · ${esc(selectedJob.issue_type)}</b></div>`;$('receiptItems').innerHTML=issues.map((x,n)=>{const i=state.items.find(y=>y.id===x.inventory_item_id)||{};return `<tr><td>${n+1}</td><td>${esc(i.equipment_type)}</td><td>${esc(i.brand)}</td><td>${esc(i.model)}</td><td>${esc(i.serial_number||'—')}</td><td>${x.quantity}</td></tr>`}).join('');$('receiptTech').textContent=(selectedJob.assigned_to||[]).map(x=>TECH_NAMES[x]).filter(Boolean).join(' / ');$('receiptDialog').showModal()}

fillOptions();$('requestDate').value=today();
document.querySelectorAll('dialog form button[value="cancel"]').forEach(button=>button.addEventListener('click',event=>{event.preventDefault();button.closest('dialog').close('cancel')}));
document.querySelectorAll('.module-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.module-tabs button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.view').forEach(x=>{x.hidden=x.id!==b.dataset.view;x.classList.toggle('active',x.id===b.dataset.view)})});
document.querySelectorAll('.switch button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.switch button').forEach(x=>x.classList.toggle('active',x===b));$('jobList').hidden=b.dataset.mode!=='list';$('calendar').hidden=b.dataset.mode!=='calendar'});
['jobSearch','jobBranchFilter','jobStatusFilter'].forEach(id=>$(id).addEventListener(id==='jobSearch'?'input':'change',renderJobs));['stockSearch','stockTypeFilter'].forEach(id=>$(id).addEventListener(id==='stockSearch'?'input':'change',renderInventory));$('branchSearch').oninput=renderBranches;
$('openJob').onclick=()=>{$('jobEmail').value=state.profile.email;$('jobName').value=`${state.profile.first_name} ${state.profile.last_name}`;$('jobDialog').showModal()};
$('jobForm').onsubmit=async e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();try{await request('POST',{action:'create-job',requestDate:$('requestDate').value,position:$('position').value,branch:$('branch').value,issueType:$('issueType').value,description:$('description').value});$('jobDialog').close();e.target.reset();$('requestDate').value=today()}catch(x){showToast(x.message,'error')}};
$('openInventory').onclick=()=>openInventoryForBranch();
$('inventoryForm').onsubmit=async e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();const base={equipmentType:$('inventoryType').value,brand:$('inventoryBrand').value,model:$('inventoryModel').value,quantity:Number($('inventoryQuantity').value),minimumQuantity:Number($('inventoryMinimum').value),branch:$('inventoryBranch').value,storageLocation:$('inventoryLocation').value,note:$('inventoryNote').value};try{const id=Number($('inventoryId').value);if(id)await request('PATCH',{action:'edit-inventory',id,...base,serialNumber:$('inventorySerial').value});else await request('POST',{action:'add-inventory',...base,serialNumbers:$('inventorySerial').value.split(',').map(x=>x.trim()).filter(Boolean)});$('inventoryDialog').close()}catch(x){showToast(x.message,'error')}};
$('saveJobEdit').onclick=async()=>{try{await request('PATCH',{action:'update-job',id:selectedJob.id,requestDate:$('editRequestDate').value,position:$('editPosition').value,branch:$('editBranch').value,issueType:$('editIssueType').value,description:$('editDescription').value,status:$('editStatus').value,scheduledDate:$('scheduledDate').value||null,assignedTo:[...document.querySelectorAll('[name=assignee]:checked')].map(x=>x.value)});$('detailDialog').close();openJob(selectedJob.id)}catch(x){showToast(x.message,'error')}};
$('deleteJob').onclick=async()=>{if(!selectedJob||!confirm(`ยืนยันลบงาน ${jobNo(selectedJob.id)}?\n\nหากงานนี้เคยตัดสต๊อก ระบบจะคืนจำนวนอุปกรณ์เข้าสต๊อกให้อัตโนมัติ`))return;try{await request('DELETE',{action:'delete-job',id:selectedJob.id});$('detailDialog').close();selectedJob=null}catch(x){showToast(x.message,'error')}};
$('issueStock').onclick=async()=>{try{await request('POST',{action:'issue-stock',jobId:selectedJob.id,inventoryItemId:Number($('issueItem').value),quantity:Number($('issueQuantity').value)});$('detailDialog').close();openJob(selectedJob.id)}catch(x){showToast(x.message,'error')}};
document.addEventListener('click',async e=>{const job=e.target.closest('[data-job]'),edit=e.target.closest('[data-edit-item]'),del=e.target.closest('[data-delete-item]'),branch=e.target.closest('[data-branch]'),addBranch=e.target.closest('[data-add-branch]'),repair=e.target.closest('[data-repair-item]');if(job)openJob(job.dataset.job);if(edit)editItem(edit.dataset.editItem);if(branch)openBranch(branch.dataset.branch);if(addBranch)openInventoryForBranch(addBranch.dataset.addBranch);if(del&&confirm('ยืนยันลบรายการอุปกรณ์นี้?\n\nเมื่อลบแล้วจะไม่สามารถเรียกคืนข้อมูลได้'))try{const branchName=$('branchDialog').open?$('branchTitle').textContent:'';await request('DELETE',{action:'delete-inventory',id:Number(del.dataset.deleteItem)});if(branchName)renderBranchDevices(branchName)}catch(x){showToast(x.message,'error')}if(repair)try{await request('POST',{action:'complete-repair',inventoryItemId:Number(repair.dataset.repairItem)})}catch(x){showToast(x.message,'error')}});
$('closeBranch').onclick=()=>$('branchDialog').close();$('receiptButton').onclick=showReceipt;$('closeReceipt').onclick=()=>$('receiptDialog').close();$('printReceipt').onclick=()=>window.print();$('logout').onclick=()=>{clearSession();location.replace('./login.html')};
load().catch(x=>showToast(x.message,'error'));

export const _test={jobNo,ALL_BRANCHES,TYPES,POSITIONS,STATUS};
